[project]
name = 'Decentralized-Traditional-Ecological-Knowledge-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.conservation-practice]
path = 'contracts/conservation-practice.clar'
clarity_version = 2
epoch = 2.5

[contracts.knowledge-registering]
path = 'contracts/knowledge-registering.clar'
clarity_version = 2
epoch = 2.5

[contracts.seasonal-indicator]
path = 'contracts/seasonal-indicator.clar'
clarity_version = 2
epoch = 2.5

[contracts."sensational-d=indicnator"]
path = 'contracts/sensational-d=indicnator.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
